### ISSUE TITLE
Assessment Results

### ISSUE THREAD

**Issue by timomitchel** [KevDev90/mod_0_skills#1]
# Checklist/Rubric

### Part I: Creating Directories and Files; Initializing Git and Pushing to GitHub

- [ ] I named my directories correctly.
No classes directory
- [x] I named my files correctly.
- [ ] I structured my files and directories correctly.
Classes directory should hold class files
- [x] I made one initial commit.
- [x] I pushed my initial commit to GitHub.

### Part II: Top Down Design

- [x] I broke down larger processes into smaller layers.
- [ ] I added and committed my changes with a properly formatted commit message starting with a present-tense verb and a capital letter.
Firs word not capitalized - We also want present tense verbs, so `change` instead of `changes`.
- [x] I pushed my changes to Github. 

### Part III: Classes, Objects, Attributes, and Methods

Class #1 Checklist
We name our classes singularly, so `Worker` instead of `Workers`.
- [x] I structured and named my directories and files correctly.
- [x] The four attributes I chose for **Class #1** represent properties or characteristics.
- [x] I identified the data type (string, integer, boolean, array, hash/object, datetime) for attributes in **Class 1**.
Salary makes more sense as a float or integer considering it would be involved in some sort of math (promote worker would add to this attribute). And good_worker and bad_worker are redundant as booleans. We only need one. If one is true then it implies the other is false.
- [x] The four methods I chose for **Class #1** represent behaviors or actions.
- [ ] I described what the methods do in **Class 1**, including which attributes they use or modify.
No description or attributes chosen to modify
- [ ] I added and committed the `class_1.txt` file **separately** with a properly formatted commit message.
Committed with other class/object files

Class #1 Example Object Checklist
- [x] The object I chose for **Class 1** is an instance of this class. 
- [x] I listed the values for each attribute of this object. 
- [x] I listed the results of each method for this object. 
- [ ] I added and committed the `class_1_example_object.txt` file **separately** with a properly formatted commit message.

Class #2 Checklist
- [x] The four attributes I chose for **Class #2** represent states or characteristics.
- [x] I identified the data type (string, integer, boolean, array, hash/object, datetime) for attributes in **Class 2**.
- [x] The four methods I chose for **Class #2** represent behaviors or actions.
- [ ] I described what the methods do in **Class 2**, including which attributes they use or modify.
- [ ] I added and committed the `class_2.txt` file **separately** with a properly formatted commit message. 

Class #2 Example Object Checklist
- [x] The object I chose for **Class 2** is an instance of this class. 
- [x] I listed the values for each attribute of this object.
The strings should be listed with quotes around them
- [x] I listed the results of each method for this object.
Methods need to be the same across class and object files. 
- [ ] I added and committed the `class_2_example_object.txt` file **separately** with a properly formatted commit message. 

Hey Kevin. This assessment is not quite up to par currently. But, we want to give you a chance to add to it after taking in the feedback from your results. We want you to add to your assessment by thinking of a class that you would find in a furniture store. Create a directory named `classes`, and within that directory create the class file named class_3.txt. Make sure it has a  proper class name with 4 attributes and  4 methods that modify the attributes that you choose, and make sure to consider the feedback around what was off in your first attempt. Add and commit these additions to class_3.txt **separately** from any other changes you introduce with a properly formatted commit message. Remember to capitalize the first word and use the present tense of the verb you start your message with. Create a file named class_3_example_object.txt within your `classes` directory and make sure this example represents an instance of whatever class you chose to model in the furniture store. Give the attributes you came up with in your class values that clearly represent their data type and show us hot the methods change an attribute. Add and commit this file **separately** with a properly formatted commit message. Push your changes to Github. Send us a message when you've made these changes, so we can review and provide feedback. 

### Assessment Results
- [ ] Technical Ready
- [x] Pending
- [ ] Not Technical Ready
